# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(450, 700)
        Login.setMaximumSize(QtCore.QSize(450, 700))
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Head = QtWidgets.QFrame(self.centralwidget)
        self.Head.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Head.setStyleSheet("")
        self.Head.setObjectName("Head")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Head)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.Head)
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/requires-interpreter.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameapp = QtWidgets.QLabel(self.Head)
        self.nameapp.setMaximumSize(QtCore.QSize(2000, 30))
        self.nameapp.setObjectName("nameapp")
        self.horizontalLayout_2.addWidget(self.nameapp)
        spacerItem = QtWidgets.QSpacerItem(739, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.hideButton = QtWidgets.QPushButton(self.Head)
        self.hideButton.setMaximumSize(QtCore.QSize(30, 30))
        self.hideButton.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"  \n"
"}\n"
"\n"
"QPushButton:hover {    \n"
"    background-color:rgb(217, 217, 217);\n"
"   \n"
"}\n"
"\n"
"\n"
"")
        self.hideButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/icons8-minimize-window-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hideButton.setIcon(icon)
        self.hideButton.setIconSize(QtCore.QSize(30, 30))
        self.hideButton.setFlat(True)
        self.hideButton.setObjectName("hideButton")
        self.horizontalLayout_2.addWidget(self.hideButton)
        self.quitButtion = QtWidgets.QPushButton(self.Head)
        self.quitButtion.setMaximumSize(QtCore.QSize(30, 30))
        self.quitButtion.setStyleSheet("QPushButton {\n"
"    background-color: rgb(244, 67, 54);\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover {    \n"
"    background-color:rgb(206, 0, 0);\n"
" \n"
"}\n"
"\n"
"\n"
"")
        self.quitButtion.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/icons8-close-window-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButtion.setIcon(icon1)
        self.quitButtion.setIconSize(QtCore.QSize(30, 30))
        self.quitButtion.setFlat(True)
        self.quitButtion.setObjectName("quitButtion")
        self.horizontalLayout_2.addWidget(self.quitButtion)
        self.verticalLayout_8.addWidget(self.Head)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.signQwidget = QtWidgets.QWidget()
        self.signQwidget.setObjectName("signQwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.signQwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.signQwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBack = QtWidgets.QPushButton(self.frame_2)
        self.btnBack.setMaximumSize(QtCore.QSize(40, 40))
        self.btnBack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon2)
        self.btnBack.setIconSize(QtCore.QSize(40, 40))
        self.btnBack.setFlat(True)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setContentsMargins(40, -1, -1, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.txtEmail = QtWidgets.QLineEdit(self.frame_8)
        self.txtEmail.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("background:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txtEmail.setObjectName("txtEmail")
        self.verticalLayout_10.addWidget(self.txtEmail)
        self.txtPassword_regi2 = QtWidgets.QLineEdit(self.frame_8)
        self.txtPassword_regi2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtPassword_regi2.setFont(font)
        self.txtPassword_regi2.setStyleSheet("background:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txtPassword_regi2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword_regi2.setObjectName("txtPassword_regi2")
        self.verticalLayout_10.addWidget(self.txtPassword_regi2)
        self.txtPassword_regi = QtWidgets.QLineEdit(self.frame_8)
        self.txtPassword_regi.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtPassword_regi.setFont(font)
        self.txtPassword_regi.setStyleSheet("background:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txtPassword_regi.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword_regi.setObjectName("txtPassword_regi")
        self.verticalLayout_10.addWidget(self.txtPassword_regi)
        self.verticalLayout.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnRegister = QtWidgets.QPushButton(self.frame_11)
        self.btnRegister.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnRegister.setFont(font)
        self.btnRegister.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgb(209,212,206);\n"
"color:rgb(0,0,0);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(182,183,181);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color:rgb(166,169,164);\n"
"}")
        self.btnRegister.setObjectName("btnRegister")
        self.horizontalLayout_4.addWidget(self.btnRegister)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_5.setContentsMargins(85, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.mess_sign = QtWidgets.QStackedWidget(self.frame_9)
        self.mess_sign.setObjectName("mess_sign")
        self.notg = QtWidgets.QWidget()
        self.notg.setObjectName("notg")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.notg)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.notoke = QtWidgets.QLabel(self.notg)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.notoke.setFont(font)
        self.notoke.setObjectName("notoke")
        self.verticalLayout_9.addWidget(self.notoke)
        self.mess_sign.addWidget(self.notg)
        self.pr = QtWidgets.QWidget()
        self.pr.setObjectName("pr")
        self.pwd_r = QtWidgets.QLabel(self.pr)
        self.pwd_r.setGeometry(QtCore.QRect(10, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pwd_r.setFont(font)
        self.pwd_r.setObjectName("pwd_r")
        self.mess_sign.addWidget(self.pr)
        self.ok = QtWidgets.QWidget()
        self.ok.setObjectName("ok")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.ok)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.oke = QtWidgets.QLabel(self.ok)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.oke.setFont(font)
        self.oke.setObjectName("oke")
        self.horizontalLayout_6.addWidget(self.oke)
        self.mess_sign.addWidget(self.ok)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.mess_sign.addWidget(self.page_4)
        self.horizontalLayout_5.addWidget(self.mess_sign)
        self.verticalLayout.addWidget(self.frame_9)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame)
        self.stackedWidget.addWidget(self.signQwidget)
        self.loginQwidget = QtWidgets.QWidget()
        self.loginQwidget.setObjectName("loginQwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginQwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.loginQwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("icon/Logo_PTIT_University.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.loginQwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.txtPassword = QtWidgets.QLineEdit(self.frame_5)
        self.txtPassword.setGeometry(QtCore.QRect(50, 120, 300, 27))
        self.txtPassword.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("background:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.txtUsername = QtWidgets.QLineEdit(self.frame_5)
        self.txtUsername.setGeometry(QtCore.QRect(50, 50, 300, 30))
        self.txtUsername.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("background:rgba(0,0,0,0);\n"
"border:1px solid rgba(0,0,0,0);\n"
"border-bottom-color:rgba(46,82,101,255);\n"
"color:rgb(0,0,0);\n"
"padding-bottom:7px\n"
"")
        self.txtUsername.setObjectName("txtUsername")
        self.fail_login = QtWidgets.QLabel(self.frame_5)
        self.fail_login.setGeometry(QtCore.QRect(90, 180, 179, 16))
        self.fail_login.setMaximumSize(QtCore.QSize(300, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fail_login.setFont(font)
        self.fail_login.setAlignment(QtCore.Qt.AlignCenter)
        self.fail_login.setObjectName("fail_login")
        self.verticalLayout_5.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(120, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnLogin = QtWidgets.QPushButton(self.frame_6)
        self.btnLogin.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgb(209,212,206);\n"
"color:rgb(0,0,0);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(182,183,181);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color:rgb(166,169,164);\n"
"}")
        self.btnLogin.setObjectName("btnLogin")
        self.verticalLayout_7.addWidget(self.btnLogin)
        self.pushButton = QtWidgets.QPushButton(self.frame_6)
        self.pushButton.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.pushButton.setFont(font)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.loginQwidget)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        self.stackedWidget.setCurrentIndex(1)
        self.mess_sign.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.nameapp.setText(_translate("Login", "Ứng dụng dịch thủ ngữ"))
        self.txtEmail.setPlaceholderText(_translate("Login", "Email"))
        self.txtPassword_regi2.setPlaceholderText(_translate("Login", "Nhập lại mật khẩu"))
        self.txtPassword_regi.setPlaceholderText(_translate("Login", "Mật khẩu"))
        self.btnRegister.setText(_translate("Login", "Đăng ký tài khoản"))
        self.notoke.setText(_translate("Login", "Đăng kí không thành công"))
        self.pwd_r.setText(_translate("Login", "Mật khẩu không trùng"))
        self.oke.setText(_translate("Login", "Đăng kí thành công !"))
        self.txtPassword.setPlaceholderText(_translate("Login", "Mật khẩu"))
        self.txtUsername.setPlaceholderText(_translate("Login", "Tên đăng nhập"))
        self.fail_login.setText(_translate("Login", "Đăng nhập không thành công !!"))
        self.btnLogin.setText(_translate("Login", "Đăng nhập"))
        self.pushButton.setText(_translate("Login", "Đăng kí tài khoản"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
